services:
  db:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_DB: time_manager
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    # restart: always
    ports:
      - "5432:5432"
    volumes:
      - "database:/var/lib/postgresql/data/"

  backend:
    build: .
    depends_on:
      - db
    # environment:
    # MIX_ENV: dev
    # env_file:
    # - .env
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "4000:4000"
    volumes:
      - .:/app

volumes:
  database:
