services:
  db:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    # restart: always
    ports:
      - "5432:5432"
    volumes:
      - "database:/var/lib/postgresql/data/"

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    depends_on:
      - db
    environment:
      MIX_ENV: prod
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}

    ports:
      - 127.0.0.1:4000:4000

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 127.0.0.1:4173:4173
    # volumes:
    #   - ./frontend/:/app/frontend
    #   - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  database:
