services:
  db:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    # restart: always
    ports:
      - "5432:5432"
    volumes:
      - "database:/var/lib/postgresql/data/"

  backend:
    image: "ghcr.io/epitechmscpropromo2026/teams/t-poo-700-stg_1/time-manager-backend:v1"
    depends_on:
      - db
    environment:
      MIX_ENV: prod
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      OVH_SMTP_USERNAME: ${OVH_SMTP_USERNAME}
      OVH_SMTP_PASSWORD: ${OVH_SMTP_PASSWORD}
    ports:
      # - 4000:4000
      - 127.0.0.1:4000:4000

  frontend:
    image: "ghcr.io/epitechmscpropromo2026/teams/t-poo-700-stg_1/time-manager-frontend:v1"
    ports:
      # - 4173:4173
      - 127.0.0.1:4173:4173
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  database:
