services:
  db:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_DB: time_manager
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    # restart: always
    ports:
      - "5432:5432"
    volumes:
      - "database:/var/lib/postgresql/data/"

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    depends_on:
      - db
    # environment:
    # MIX_ENV: dev
    # env_file:
    # - .env
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "4000:4000"
    volumes:
      # - ./backend/:/app/backend
      - ./backend/.elixir-tools:/app/backend/.elixir-tools
      - ./backend/_build:/app/backend/_build
      - ./backend/assets:/app/backend/assets
      - ./backend/config:/app/backend/config
      - ./backend/deps:/app/backend/deps
      - ./backend/lib:/app/backend/lib:cached
      - ./backend/priv:/app/backend/priv:cached
      - ./backend/test:/app/backend/test

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/:/app/frontend
      - /app/node_modules
    stdin_open: true
    tty: true

  zap:
    image: zaproxy/zap-stable
    container_name: zap
    ports:
      - "8080:8080"
      - "8090:8090"
    command: >
      sh -c "zap-webswing.sh"

volumes:
  database:
