global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'backend'
    static_configs:
      - targets: ['localhost:4000']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:5173']

  - job_name: 'db'
    static_configs:
      - targets: ['db:5432']

  - job_name: 'graphana'
    static_configs:
      - targets: ['graphana:3000']
  
  - job_name: 'zap'
    static_configs:
      - targets: ['zap:8070']
