name: CI/CD Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - prod

jobs:
  build:
    runs-on: self-hosted

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: timemanager
          POSTGRES_PASSWORD: timemanager
          POSTGRES_DB: timemanager_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      # Set up Node.js if you have a frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      # - name: Start PostgreSQL on Ubuntu
      #   run: |
      #     sudo systemctl start postgresql.service
      #     pg_isready
      #
      # - name: Create additional user
      #   run: |
      #     sudo -u postgres psql --command="CREATE USER test_user WITH PASSWORD 'test_password'" --command="\du"
      #
      # - name: Create additional database
      #   run: |
      #     sudo -u postgres createdb test_database --owner=test_user
      #     PGPASSWORD=test_password

      # Install dependencies
      - run: rm -rf nodes_modules
        working-directory: ./frontend
      - run: rm -f package-lock.json
        working-directory: ./frontend
      - run: npm install
        working-directory: ./frontend

      # Run frontend build
      - run: npm run build
        working-directory: ./frontend

      # Set up Elixir if you have a backend
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.17.3" # Specify your Elixir version
          otp-version: "27" # Specify OTP version

      # Install Elixir dependencies
      - run: mix deps.get
        working-directory: ./backend

      - run: echo "DATABASE_URL=ecto://test_user:test_password@localhost:5432/test_database" >> $GITHUB_ENV
        working-directory: ./backend

      - run: mix setup
        working-directory: ./backend

      # Run backend tests
      # - run: mix ecto.reset
      # working-directory: ./backend
      # - run: mix test test/time_manager_web/controllers/clock_controller_test.exs
      #   working-directory: ./backend
      # - run: mix test test/time_manager_web/controllers/user_controller_test.exs
      #   working-directory: ./backend
      # - run: mix test test/time_manager_web/controllers/working_time_controller_test.exs
      #   working-directory: ./backend
